name: Daily Commit

on:
  workflow_dispatch: # Habilita la ejecución manual
  schedule:
    - cron: '0 0 * * *' # Ejecuta el flujo de trabajo diariamente a medianoche UTC

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Run daily commit script
      run: node dist/dailyCommit.js
