name: Daily Commit

on:
  workflow_dispatch: # Habilita la ejecución manual
  schedule:
    - cron: '0 0 * * *' # Ejecuta diariamente a medianoche UTC

jobs:
  daily-commit:
    runs-on: ubuntu-latest

    steps:
    # Paso 1: Clonar el repositorio
    - name: Checkout code
      uses: actions/checkout@v3

    # Paso 2: Realizar el commit diario
    - name: Make daily commit
      run: |
        echo "Commit realizado el: $(date)" >> daily-log.txt
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add daily-log.txt
        git commit -m "Daily commit - $(date)"
        git push
